# Generated by Django 5.1.6 on 2025-04-06 09:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Girls image')),
                ('disc_img', models.ImageField(upload_to='Images', verbose_name='Discount image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('sub_bool', models.BooleanField(default=True, null=True, verbose_name='Has sub. or not')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Items name(category)')),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Site name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(verbose_name='Faceboook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
                ('dribbble', models.URLField(verbose_name='Dribbble')),
                ('googleplus', models.URLField(verbose_name='Google Plus')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Logoname')),
                ('info', models.TextField(null=True, verbose_name='Text')),
                ('owner', models.CharField(max_length=20, null=True, verbose_name='Owner')),
                ('add', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Addvertisement')),
                ('map_img', models.ImageField(null=True, upload_to='Images', verbose_name='Map')),
                ('adress', models.CharField(max_length=255, null=True, verbose_name='Adress')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_code', models.IntegerField(verbose_name='Verification code')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50, verbose_name='Category name')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat_rn', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Image')),
                ('info', models.TextField(verbose_name='Info')),
                ('brand', models.CharField(max_length=30, verbose_name='Brand')),
                ('reccomend_bool', models.BooleanField(default=False, verbose_name='Reccom. or not')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('disc_icon', models.ImageField(null=True, upload_to='', verbose_name='Discount Icon')),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rn', to='main.category')),
                ('key3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsname_rn', to='main.itemsname')),
                ('key2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_rn', to='main.subcategory')),
            ],
        ),
    ]
