# Generated by Django 5.1.6 on 2025-04-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreinfo', models.TextField(verbose_name='Description')),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('condition', models.BooleanField(verbose_name='Condition')),
                ('condition_img', models.ImageField(null=True, upload_to='Images', verbose_name='Logo <New>')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_details_rn', to='main.items')),
            ],
        ),
    ]
