# Generated by Django 5.1.6 on 2025-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itemsimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Image')),
                ('desc', models.TextField(null=True, verbose_name='Description')),
                ('date', models.CharField(max_length=30, null=True, verbose_name='Date')),
            ],
        ),
    ]
