# Generated by Django 5.1.6 on 2025-04-06 20:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='model404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Images', verbose_name='error Image')),
            ],
        ),
        migrations.CreateModel(
            name='Total_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eco_Tax', models.IntegerField(verbose_name='Eco Tax Price')),
                ('Shipping_Cost', models.IntegerField(verbose_name='Shipping_Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Payments_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=255, verbose_name='Payment')),
                ('Payment_date', models.DateField(auto_now_add=True, null=True, verbose_name='Payments date')),
                ('Payments_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Payments time')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5, null=True)),
                ('review_date', models.DateField(auto_now_add=True, null=True, verbose_name='Reviews date')),
                ('review_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Reviews time')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_rn', to='main.items')),
            ],
        ),
        migrations.CreateModel(
            name='UserFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_code', models.IntegerField(blank=True, null=True, verbose_name='verification code')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name="User's name")),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name="User's surname")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name="User's phone number")),
                ('adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery adress')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Items number in cart')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_rn', to='main.items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
