# Generated by Django 5.1.6 on 2025-04-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmessage_model404_total_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersave',
            old_name='item_id',
            new_name='item_key',
        ),
        migrations.RenameField(
            model_name='usersave',
            old_name='user_id',
            new_name='user_key',
        ),
        migrations.DeleteModel(
            name='UserFor',
        ),
    ]
