# Generated by Django 5.1.6 on 2025-04-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_item_id_usersave_item_key_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Total_payment',
            new_name='Total_Taxes',
        ),
    ]
